theme: jekyll-theme-minimal
logo: xinyuan.jpg
title: Xinyuan's homepage 
description: Xinyuan Ji is now working at Leiden University. She is a joint program PhD of Xi’an Jiaotong University and Leiden University. Her research interests include distributed computing, data mining, machine learning, federated learning and privacy & security. Feel free to contact Xinyuan if you have questions, seek academic cooperation  or just want to make friends.